import { ClerkProvider } from '@/components/clerk-provider'
import { Header } from '@/components/header'
import { ThemeProvider } from '@/components/theme-provider'
// Link moved to components where needed
import FloatingFooter from '@/components/floating-footer'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} flex min-h-full flex-col antialiased pb-28`}>
          {/* Demo badge — visible on every page to indicate this is a demo site */}
          <div className="fixed left-1/2 -translate-x-1/2 z-[999999] top-4 " style={{ top: 'env(safe-area-inset-top, 16px)' }}>
            <div className="bg-yellow-400 text-black px-3 py-1 rounded-full shadow animate-pulse text-sm font-medium mt-4">DEMO — Not for production</div>
          </div>

            {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange> */}
              {/* <Header /> */}
              {children}

              <FloatingFooter />
            {/* </ThemeProvider> */}
        </body>
      </html>
    </ClerkProvider>
  )
}
